version: '3.7'
services:

    nginx:
        image: nginx:latest
        container_name: library_nginx
        depends_on: 
            - node
            - mongo
        volumes:
            - ./nginx:/etc/nginx/conf.d
        ports:
            - "80:80"
        networks: 
            - overlay
    
    node:
        image: node:latest
        container_name: library_node
        volumes: 
            - ../library-vue3:/home/node/library-vue3
            - ../library-loopback4:/home/node/library-loopback4
            - .:/home/node/library-infra
        working_dir: /home/node/library-infra
        command: bash -c "npm install pm2 -g && pm2-runtime ecosystem.config.js"

        ports:
            - "3000:3000"
            - "3001:3001"
        networks:
            - overlay
                    
    mongo:
        image: mongo:latest
        container_name: library_mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: rootpassword
        ports:
            - 27017:27017
        networks: 
            - overlay
        volumes:
            - mongodb_data_container:/data/db
            
volumes:
    mongodb_data_container:

networks: 
    overlay: